### ISSUE TITLE
Remain on 1.13.2

### ISSUE THREAD

**Issue by Demeng7215** [kangarko/Remain#1]
Hello,
Am I still able to use Remain with the 1.13.2 API, and run the plugin on a 1.8 server? One of my plugin users are getting an NPE when they use RED_WOOL.

**Comment by kangarko** [comment]
Hi,

use the latest version of Remain as well as SpigotAPI 1.14.1. I just pushed a new release tag 3.2.0, use that. If still does not work, please post me the error in full.

**Comment by Demeng7215** [comment]
Should api-version in plugin.yml still be 1.13?

**Comment by kangarko** [comment]
Yes, it's backward compatible for now.
