### ISSUE TITLE
RuntimeException on #setPlugin()

### ISSUE THREAD

**Issue by Demeng7215** [kangarko/Remain#3]
One of my plugin users are currently getting this error:
https://images-ext-1.discordapp.net/external/Dt23wDk8TZqHurY4ne5RAE3A7UM8KvWMPfFJlLr8aKw/https/i.gyazo.com/thumb/1200/304cf9923b6bc443f41fa5893ca8b724-png.jpg
Have no idea what this is, line 46 of RankGrantPlus.java is Remain.setPlugin(this).
User is running 1.7.

**Comment by kangarko** [comment]
I am sorry, remain is unsupported for 1.7 and requires 1.8 at minimum.
