### ISSUE TITLE
toItem() method issue

### ISSUE THREAD

**Issue by lulu2002** [kangarko/Remain#9]
public final ItemStack toItem(int amount) {
        final Material mat = toMaterial();

        return MinecraftVersion.atLeast(MinecraftVersion.V.v1_13) ? new ItemStack(mat, amount) : new ItemStack(mat, amount, (byte) data);
    }

The byte should change to "short", or it sometimes will cause issue like when I cover ROSE_RED to Itemstack.

**Comment by lulu2002** [comment]
Oh wait, it seems like is toMaterial() issue, it can not match ROSE_RED to material in a server that version lower than 1.13.

**Comment by lulu2002** [comment]
Ok I found where the problem is, the color dye's legacyName and alternativeName should be swap.

ex: GREEN_DYE("CACTUS_GREEN", "INK_SACK", 2) -> GREEN_DYE("INK_SACK", "CACTUS_GREEN", 2)

**Comment by kangarko** [comment]
Thank you!
